reset_cartridge:
  name: Reset Cartridge
  description: Reset the cartridge runtime counter to zero for the specified bus.
  target:
    entity:
      domain: light
      integration: repelbridge
  fields:
    bus_id:
      name: Bus ID
      description: The bus ID (0 or 1) to reset the cartridge for.
      required: true
      selector:
        select:
          options:
            - label: "Bus 0"
              value: 0
            - label: "Bus 1"
              value: 1